{{- $fullName := include "otel.fullname" . -}}
{{- $svcPort := 8080 -}}
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: humio-agent-cluster
  labels:
    {{- include "otel.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    
spec:
  serviceAccount: {{ include "otel.serviceAccountName" . }}-otel
  image: otel/opentelemetry-collector-contrib:0.56.0
  mode: deployment
  env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: HUMIO_TOKEN_K8S_LOGS
          valueFrom:
            secretKeyRef:
                name: {{ .Values.humiosecretprefix }}-all-humio-infra-k8s-logs  
                key: token
        - name: HUMIO_TOKEN_K8S_METRICS
          valueFrom:
            secretKeyRef:
                name: {{ .Values.humiosecretprefix }}-all-humio-infra-k8s-metrics  
                key: token
  config: |
    exporters:
        splunk_hec/k8s_logs:
            endpoint: "{{ .Values.humioservice }}"
            token: $HUMIO_TOKEN_K8S_LOGS
        splunk_hec/k8s_metrics:
            endpoint: "{{ .Values.humioservice }}"
            token: $HUMIO_TOKEN_K8S_METRICS
    receivers:
      k8s_events:
      k8s_cluster:
        node_conditions_to_report:
          [Ready, DiskPressure, MemoryPressure, PIDPressure, NetworkUnavailable]
        allocatable_types_to_report: [cpu, memory]
      kubeletstats:
        auth_type: "serviceAccount"
        endpoint: "https://${K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
        extra_metadata_labels:
          - container.id
          - k8s.volume.type
    processors:
      batch:
      resourcedetection:
        detectors: [env, azure]
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.cluster.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
        pod_association:
          - from: resource_attribute
            name: k8s.pod.uid

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        metrics:
          receivers: [k8s_cluster, kubeletstats]
          processors: [batch]
          exporters: [splunk_hec/k8s_metrics]
        logs:
          receivers: [k8s_events]
          processors: [batch]
          exporters: [splunk_hec/k8s_logs]